//
//  APIModel.swift
//  swifty-companion
//
//  Created by Sylvain BONNEFON on 4/25/19.
//  Copyright © 2019 sbonnefo. All rights reserved.
//

import Foundation


struct TokenAPI: Codable {
    var access_token: String?
    var created_at: Double?
    var expires_in: Double?
    var expire_date: Date?
}

struct userInfo: Codable {
    
}

//
//sbonnefo :
//{
//    "id":20021,
//    "email":"sbonnefo@student.42.fr",
//    "login":"sbonnefo",
//    "first_name":"Sylvain",
//    "last_name":"Bonnefon",
//    "url":"https://api.intra.42.fr/v2/users/sbonnefo",
//    "phone":"+33610587883",
//    "displayname":"Sylvain Bonnefon",
//    "image_url":"https://cdn.intra.42.fr/users/sbonnefo.jpg",
//    "staff?":false,
//    "correction_point":50,
//    "pool_month":"august",
//    "pool_year":"2016",
//    "location":"e1r5p23",
//    "wallet":230,
//    "groups":[
//
//    ],
//    "cursus_users":[
//    {
//          "grade":"Captain",
//          "level":14.43,
//          "skills":[
//          {
//              "id":16,
//              "name":"Company experience",
//               "level":10.77
//          },
//          {
//               "id":4,
//              "name":"Unix",
//              "level":9.96
//          },
//          {
//              "id":7,
//               "name":"Group \u0026 interpersonal",
//               "level":8.2
//          },
//           {
//              "id":17,
//              "name":"Object-oriented programming",
//              "level":6.89
//            },
//           {
//              "id":3,
//               "name":"Rigor",
               "level":5.96
    },
    {
    "id":1,
    "name":"Algorithms \u0026 AI",
    "level":5.89
    },
    {
    "id":2,
    "name":"Imperative programming",
    "level":5.89
    },
    {
    "id":15,
    "name":"Technology integration",
    "level":4.75
    },
    {
    "id":6,
    "name":"Web",
    "level":4.45
    },
    {
    "id":11,
    "name":"Security",
    "level":3.58
    },
    {
    "id":14,
    "name":"Adaptation \u0026 creativity",
    "level":2.4
    },
    {
    "id":12,
    "name":"DB \u0026 Data",
    "level":1.8199999999999998
    },
    {
    "id":13,
    "name":"Organization",
    "level":1.52
    },
    {
    "id":10,
    "name":"Network \u0026 system administration",
    "level":1.52
    },
    {
    "id":5,
    "name":"Graphics",
    "level":1.28
    },
    {
    "id":9,
    "name":"Parallel computing",
    "level":1.1
    }
    ],
    "id":15649,
    "begin_at":"2016-11-02T08:00:00.000Z",
    "end_at":null,
    "cursus_id":1,
    "has_coalition":true,
    "user":{
    "id":20021,
    "login":"sbonnefo",
    "url":"https://api.intra.42.fr/v2/users/sbonnefo"
    },
    "cursus":{
    "id":1,
    "created_at":"2014-11-02T16:43:38.480Z",
    "name":"42",
    "slug":"42"
    }
    },
    {
    "grade":null,
    "level":6.35,
    "skills":[
    {
    "id":1,
    "name":"Algorithms \u0026 AI",
    "level":7.0
    },
    {
    "id":3,
    "name":"Rigor",
    "level":6.04
    },
    {
    "id":4,
    "name":"Unix",
    "level":5.79
    },
    {
    "id":7,
    "name":"Group \u0026 interpersonal",
    "level":0.39
    }
    ],
    "id":12147,
    "begin_at":"2016-08-01T06:42:00.000Z",
    "end_at":"2016-08-26T16:00:00.000Z",
    "cursus_id":6,
    "has_coalition":true,
    "user":{
    "id":20021,
    "login":"sbonnefo",
    "url":"https://api.intra.42.fr/v2/users/sbonnefo"
    },
    "cursus":{
    "id":6,
    "created_at":"2015-09-21T12:36:09.128Z",
    "name":"Piscine C décloisonnée",
    "slug":"piscine-c-decloisonnee"
    }
    }
    ],
    "projects_users":[
    {
    "id":314128,
    "occurrence":2,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":1339137,
    "project":{
    "id":154,
    "name":"Day 00",
    "slug":"piscine-c-day-00",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-03T14:06:20.339Z",
    "marked":true
    },
    {
    "id":314156,
    "occurrence":2,
    "final_mark":60,
    "status":"finished",
    "validated?":true,
    "current_team_id":1340789,
    "project":{
    "id":155,
    "name":"Day 01",
    "slug":"piscine-c-day-01",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-04T14:29:41.829Z",
    "marked":true
    },
    {
    "id":316474,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":false,
    "current_team_id":1338564,
    "project":{
    "id":404,
    "name":"Exam00",
    "slug":"piscine-c-exam00",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-11-07T11:31:49.231Z",
    "marked":true
    },
    {
    "id":317210,
    "occurrence":1,
    "final_mark":80,
    "status":"finished",
    "validated?":true,
    "current_team_id":1343302,
    "project":{
    "id":156,
    "name":"Day 02",
    "slug":"piscine-c-day-02",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-07T06:22:20.961Z",
    "marked":true
    },
    {
    "id":317222,
    "occurrence":0,
    "final_mark":120,
    "status":"finished",
    "validated?":true,
    "current_team_id":1342887,
    "project":{
    "id":168,
    "name":"Rush 00",
    "slug":"piscine-c-rush-00",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-09T14:44:45.018Z",
    "marked":true
    },
    {
    "id":317959,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":false,
    "current_team_id":1341087,
    "project":{
    "id":171,
    "name":"Sastantua",
    "slug":"piscine-c-sastantua",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-08T18:53:54.639Z",
    "marked":true
    },
    {
    "id":318223,
    "occurrence":2,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":1385461,
    "project":{
    "id":157,
    "name":"Day 03",
    "slug":"piscine-c-day-03",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-21T20:40:51.718Z",
    "marked":true
    },
    {
    "id":319979,
    "occurrence":1,
    "final_mark":85,
    "status":"finished",
    "validated?":true,
    "current_team_id":1351829,
    "project":{
    "id":158,
    "name":"Day 04",
    "slug":"piscine-c-day-04",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-10T20:14:00.737Z",
    "marked":true
    },
    {
    "id":321974,
    "occurrence":2,
    "final_mark":64,
    "status":"finished",
    "validated?":true,
    "current_team_id":1374386,
    "project":{
    "id":159,
    "name":"Day 05",
    "slug":"piscine-c-day-05",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-16T15:01:31.419Z",
    "marked":true
    },
    {
    "id":322192,
    "occurrence":0,
    "final_mark":22,
    "status":"finished",
    "validated?":false,
    "current_team_id":1347115,
    "project":{
    "id":167,
    "name":"Day 09",
    "slug":"piscine-c-day-09",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-13T12:11:36.181Z",
    "marked":true
    },
    {
    "id":326615,
    "occurrence":0,
    "final_mark":6,
    "status":"finished",
    "validated?":false,
    "current_team_id":1351571,
    "project":{
    "id":405,
    "name":"Exam01",
    "slug":"piscine-c-exam01",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-12T20:00:00.470Z",
    "marked":true
    },
    {
    "id":326613,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":false,
    "current_team_id":1371213,
    "project":{
    "id":169,
    "name":"Rush 01",
    "slug":"piscine-c-rush-01",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-18T13:25:21.167Z",
    "marked":true
    },
    {
    "id":326618,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":false,
    "current_team_id":1351574,
    "project":{
    "id":172,
    "name":"Match-N-Match",
    "slug":"piscine-c-match-n-match",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-15T07:59:40.806Z",
    "marked":true
    },
    {
    "id":439822,
    "occurrence":1,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":1473896,
    "project":{
    "id":817,
    "name":"42 Commandements",
    "slug":"42-formation-pole-emploi-42-commandements",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2016-11-16T09:56:42.320Z",
    "marked":true
    },
    {
    "id":439842,
    "occurrence":3,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":1477841,
    "project":{
    "id":756,
    "name":"Piscine Reloaded",
    "slug":"piscine-reloaded",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2016-11-28T19:22:08.264Z",
    "marked":true
    },
    {
    "id":330652,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1355935,
    "project":{
    "id":188,
    "name":"04",
    "slug":"piscine-c-day-09-04",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:57.200Z",
    "marked":true
    },
    {
    "id":334163,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359478,
    "project":{
    "id":198,
    "name":"14",
    "slug":"piscine-c-day-09-14",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:55.239Z",
    "marked":true
    },
    {
    "id":334185,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359500,
    "project":{
    "id":205,
    "name":"21",
    "slug":"piscine-c-day-09-21",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:53.592Z",
    "marked":true
    },
    {
    "id":334158,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359473,
    "project":{
    "id":193,
    "name":"09",
    "slug":"piscine-c-day-09-09",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:55.821Z",
    "marked":true
    },
    {
    "id":334157,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359472,
    "project":{
    "id":194,
    "name":"10",
    "slug":"piscine-c-day-09-10",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:56.053Z",
    "marked":true
    },
    {
    "id":334144,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359459,
    "project":{
    "id":189,
    "name":"05",
    "slug":"piscine-c-day-09-05",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:57.009Z",
    "marked":true
    },
    {
    "id":334173,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359488,
    "project":{
    "id":200,
    "name":"16",
    "slug":"piscine-c-day-09-16",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:54.342Z",
    "marked":true
    },
    {
    "id":334190,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359505,
    "project":{
    "id":207,
    "name":"23",
    "slug":"piscine-c-day-09-23",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:53.400Z",
    "marked":true
    },
    {
    "id":334162,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359477,
    "project":{
    "id":197,
    "name":"13",
    "slug":"piscine-c-day-09-13",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:55.443Z",
    "marked":true
    },
    {
    "id":334161,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359476,
    "project":{
    "id":195,
    "name":"11",
    "slug":"piscine-c-day-09-11",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:55.635Z",
    "marked":true
    },
    {
    "id":334152,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359467,
    "project":{
    "id":190,
    "name":"06",
    "slug":"piscine-c-day-09-06",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:56.527Z",
    "marked":true
    },
    {
    "id":334170,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359485,
    "project":{
    "id":202,
    "name":"18",
    "slug":"piscine-c-day-09-18",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:54.802Z",
    "marked":true
    },
    {
    "id":334172,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359487,
    "project":{
    "id":199,
    "name":"15",
    "slug":"piscine-c-day-09-15",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:54.571Z",
    "marked":true
    },
    {
    "id":334196,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359511,
    "project":{
    "id":206,
    "name":"22",
    "slug":"piscine-c-day-09-22",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:53.214Z",
    "marked":true
    },
    {
    "id":346098,
    "occurrence":2,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":1379171,
    "project":{
    "id":160,
    "name":"Day 06",
    "slug":"piscine-c-day-06",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-17T20:36:19.642Z",
    "marked":true
    },
    {
    "id":442635,
    "occurrence":0,
    "final_mark":116,
    "status":"finished",
    "validated?":true,
    "current_team_id":1478057,
    "project":{
    "id":1,
    "name":"Libft",
    "slug":"libft",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2016-12-16T17:49:28.383Z",
    "marked":true
    },
    {
    "id":347745,
    "occurrence":2,
    "final_mark":60,
    "status":"finished",
    "validated?":true,
    "current_team_id":1386087,
    "project":{
    "id":161,
    "name":"Day 07",
    "slug":"piscine-c-day-07",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-22T20:36:27.384Z",
    "marked":true
    },
    {
    "id":348484,
    "occurrence":0,
    "final_mark":59,
    "status":"finished",
    "validated?":true,
    "current_team_id":1375401,
    "project":{
    "id":406,
    "name":"Exam02",
    "slug":"piscine-c-exam02",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-19T20:00:50.566Z",
    "marked":true
    },
    {
    "id":468196,
    "occurrence":0,
    "final_mark":125,
    "status":"finished",
    "validated?":true,
    "current_team_id":1511665,
    "project":{
    "id":4,
    "name":"FdF",
    "slug":"fdf",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-06-21T18:25:53.283Z",
    "marked":true
    },
    {
    "id":354281,
    "occurrence":1,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":1387465,
    "project":{
    "id":162,
    "name":"Day 08",
    "slug":"piscine-c-day-08",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-23T17:08:57.247Z",
    "marked":true
    },
    {
    "id":444921,
    "occurrence":7,
    "final_mark":93,
    "status":"finished",
    "validated?":true,
    "current_team_id":1506360,
    "project":{
    "id":11,
    "name":"C Exam Alone In The Dark - Beginner",
    "slug":"c-exam-alone-in-the-dark-beginner",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-02-14T09:28:57.535Z",
    "marked":true
    },
    {
    "id":445599,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":1489753,
    "project":{
    "id":540,
    "name":"Fillit",
    "slug":"fillit",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-01-14T15:53:56.588Z",
    "marked":true
    },
    {
    "id":357891,
    "occurrence":1,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":1389744,
    "project":{
    "id":163,
    "name":"Day 10",
    "slug":"piscine-c-day-10",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-25T19:34:52.250Z",
    "marked":true
    },
    {
    "id":348480,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":false,
    "current_team_id":1375396,
    "project":{
    "id":173,
    "name":"EvalExpr",
    "slug":"piscine-c-evalexpr",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-22T21:44:41.814Z",
    "marked":true
    },
    {
    "id":358078,
    "occurrence":0,
    "final_mark":45,
    "status":"finished",
    "validated?":true,
    "current_team_id":1386778,
    "project":{
    "id":407,
    "name":"Exam Final",
    "slug":"piscine-c-exam-final",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-26T15:29:04.831Z",
    "marked":true
    },
    {
    "id":358773,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":false,
    "current_team_id":1387747,
    "project":{
    "id":164,
    "name":"Day 11",
    "slug":"piscine-c-day-11",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-11-07T10:59:25.588Z",
    "marked":true
    },
    {
    "id":348477,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":false,
    "current_team_id":1383472,
    "project":{
    "id":170,
    "name":"Rush 02",
    "slug":"piscine-c-rush-02",
    "parent_id":null
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2016-08-24T12:13:44.863Z",
    "marked":true
    },
    {
    "id":450053,
    "occurrence":0,
    "final_mark":15,
    "status":"finished",
    "validated?":true,
    "current_team_id":1489601,
    "project":{
    "id":659,
    "name":"Electronics Selection Test",
    "slug":"electronics-electronics-selection-test",
    "parent_id":411
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-01-30T14:04:47.147Z",
    "marked":true
    },
    {
    "id":450490,
    "occurrence":0,
    "final_mark":119,
    "status":"finished",
    "validated?":true,
    "current_team_id":1490293,
    "project":{
    "id":2,
    "name":"Get_Next_Line",
    "slug":"get_next_line",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-02-22T16:35:14.064Z",
    "marked":true
    },
    {
    "id":486846,
    "occurrence":0,
    "final_mark":109,
    "status":"finished",
    "validated?":true,
    "current_team_id":1534431,
    "project":{
    "id":3,
    "name":"ft_ls",
    "slug":"ft_ls",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-06-07T17:59:56.074Z",
    "marked":true
    },
    {
    "id":480190,
    "occurrence":0,
    "final_mark":111,
    "status":"finished",
    "validated?":true,
    "current_team_id":1528160,
    "project":{
    "id":93,
    "name":"wong_kar_wai",
    "slug":"rushes-wong_kar_wai",
    "parent_id":61
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-05-18T18:55:09.852Z",
    "marked":true
    },
    {
    "id":473639,
    "occurrence":0,
    "final_mark":null,
    "status":"parent",
    "validated?":null,
    "current_team_id":null,
    "project":{
    "id":61,
    "name":"Rushes",
    "slug":"rushes",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":566925,
    "occurrence":0,
    "final_mark":122,
    "status":"finished",
    "validated?":true,
    "current_team_id":1632142,
    "project":{
    "id":523,
    "name":"21sh",
    "slug":"21sh",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-07-27T09:44:41.685Z",
    "marked":true
    },
    {
    "id":521208,
    "occurrence":0,
    "final_mark":114,
    "status":"finished",
    "validated?":true,
    "current_team_id":1577685,
    "project":{
    "id":7,
    "name":"minishell",
    "slug":"minishell",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-07-21T09:05:00.961Z",
    "marked":true
    },
    {
    "id":698543,
    "occurrence":0,
    "final_mark":96,
    "status":"finished",
    "validated?":true,
    "current_team_id":1788765,
    "project":{
    "id":49,
    "name":"Day 00",
    "slug":"42-piscine-c-formation-piscine-php-day-00",
    "parent_id":48
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-10-04T10:02:15.549Z",
    "marked":true
    },
    {
    "id":701984,
    "occurrence":0,
    "final_mark":83,
    "status":"finished",
    "validated?":true,
    "current_team_id":1792466,
    "project":{
    "id":50,
    "name":"Day 01",
    "slug":"42-piscine-c-formation-piscine-php-day-01",
    "parent_id":48
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-10-05T09:42:44.458Z",
    "marked":true
    },
    {
    "id":703081,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":1793625,
    "project":{
    "id":52,
    "name":"Day 03",
    "slug":"42-piscine-c-formation-piscine-php-day-03",
    "parent_id":48
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-10-09T08:34:35.855Z",
    "marked":true
    },
    {
    "id":704050,
    "occurrence":0,
    "final_mark":98,
    "status":"finished",
    "validated?":true,
    "current_team_id":1794638,
    "project":{
    "id":53,
    "name":"Day 04",
    "slug":"42-piscine-c-formation-piscine-php-day-04",
    "parent_id":48
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-10-09T10:55:27.858Z",
    "marked":true
    },
    {
    "id":706527,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":1797530,
    "project":{
    "id":59,
    "name":"Rush00",
    "slug":"piscine-php-rush00",
    "parent_id":48
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-10-10T12:39:40.712Z",
    "marked":true
    },
    {
    "id":701985,
    "occurrence":0,
    "final_mark":85,
    "status":"finished",
    "validated?":true,
    "current_team_id":1792467,
    "project":{
    "id":51,
    "name":"Day 02",
    "slug":"42-piscine-c-formation-piscine-php-day-02",
    "parent_id":48
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-10-06T08:50:31.037Z",
    "marked":true
    },
    {
    "id":708342,
    "occurrence":0,
    "final_mark":60,
    "status":"finished",
    "validated?":true,
    "current_team_id":1798761,
    "project":{
    "id":55,
    "name":"Day 06",
    "slug":"42-piscine-c-formation-piscine-php-day-06",
    "parent_id":48
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-10-16T21:31:18.717Z",
    "marked":true
    },
    {
    "id":708344,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":1798763,
    "project":{
    "id":56,
    "name":"Day 07",
    "slug":"42-piscine-c-formation-piscine-php-day-07",
    "parent_id":48
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-10-13T00:47:49.046Z",
    "marked":true
    },
    {
    "id":711931,
    "occurrence":0,
    "final_mark":65,
    "status":"finished",
    "validated?":true,
    "current_team_id":1802618,
    "project":{
    "id":58,
    "name":"Day 09",
    "slug":"42-piscine-c-formation-piscine-php-day-09",
    "parent_id":48
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-10-15T17:11:41.979Z",
    "marked":true
    },
    {
    "id":342373,
    "occurrence":0,
    "final_mark":null,
    "status":"finished",
    "validated?":null,
    "current_team_id":1367902,
    "project":{
    "id":175,
    "name":"00",
    "slug":"piscine-c-day-09-00",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":342374,
    "occurrence":0,
    "final_mark":null,
    "status":"finished",
    "validated?":null,
    "current_team_id":1367903,
    "project":{
    "id":185,
    "name":"01",
    "slug":"piscine-c-day-09-01",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":342375,
    "occurrence":0,
    "final_mark":null,
    "status":"finished",
    "validated?":null,
    "current_team_id":1367904,
    "project":{
    "id":186,
    "name":"02",
    "slug":"piscine-c-day-09-02",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":342376,
    "occurrence":0,
    "final_mark":null,
    "status":"finished",
    "validated?":null,
    "current_team_id":1367905,
    "project":{
    "id":201,
    "name":"17",
    "slug":"piscine-c-day-09-17",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":461562,
    "occurrence":0,
    "final_mark":null,
    "status":"searching_a_group",
    "validated?":null,
    "current_team_id":null,
    "project":{
    "id":666,
    "name":"Electronics Project",
    "slug":"electronics-electronics-project",
    "parent_id":411
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":718476,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":false,
    "current_team_id":1809199,
    "project":{
    "id":54,
    "name":"Day 05",
    "slug":"42-piscine-c-formation-piscine-php-day-05",
    "parent_id":48
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-10-15T22:21:54.132Z",
    "marked":true
    },
    {
    "id":718477,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":false,
    "current_team_id":1809200,
    "project":{
    "id":60,
    "name":"Rush01",
    "slug":"piscine-php-rush01",
    "parent_id":48
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-10-29T22:19:14.917Z",
    "marked":true
    },
    {
    "id":574459,
    "occurrence":0,
    "final_mark":75,
    "status":"finished",
    "validated?":true,
    "current_team_id":1603063,
    "project":{
    "id":35,
    "name":"42sh",
    "slug":"42sh",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-07-28T23:09:28.353Z",
    "marked":true
    },
    {
    "id":445598,
    "occurrence":0,
    "final_mark":null,
    "status":"parent",
    "validated?":null,
    "current_team_id":null,
    "project":{
    "id":411,
    "name":"Electronics",
    "slug":"electronics",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":486847,
    "occurrence":0,
    "final_mark":null,
    "status":"in_progress",
    "validated?":null,
    "current_team_id":1534432,
    "project":{
    "id":5,
    "name":"ft_printf",
    "slug":"ft_printf",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":708346,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":false,
    "current_team_id":1798765,
    "project":{
    "id":57,
    "name":"Day 08",
    "slug":"42-piscine-c-formation-piscine-php-day-08",
    "parent_id":48
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-10-29T21:49:51.139Z",
    "marked":true
    },
    {
    "id":666574,
    "occurrence":0,
    "final_mark":null,
    "status":"in_progress",
    "validated?":null,
    "current_team_id":1749991,
    "project":{
    "id":902,
    "name":"Curriculum Vitae",
    "slug":"curriculum-vitae",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":754430,
    "occurrence":0,
    "final_mark":124,
    "status":"finished",
    "validated?":true,
    "current_team_id":1855813,
    "project":{
    "id":140,
    "name":"Duration",
    "slug":"first-internship-duration",
    "parent_id":118
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-12-19T12:50:16.694Z",
    "marked":true
    },
    {
    "id":754429,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":1855812,
    "project":{
    "id":119,
    "name":"Contract Upload",
    "slug":"first-internship-contract-upload",
    "parent_id":118
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-12-19T12:50:22.195Z",
    "marked":true
    },
    {
    "id":754431,
    "occurrence":0,
    "final_mark":101,
    "status":"finished",
    "validated?":true,
    "current_team_id":1855814,
    "project":{
    "id":826,
    "name":"Company mid evaluation",
    "slug":"first-internship-company-mid-evaluation",
    "parent_id":118
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-04-04T13:40:35.437Z",
    "marked":true
    },
    {
    "id":754432,
    "occurrence":0,
    "final_mark":101,
    "status":"finished",
    "validated?":true,
    "current_team_id":1855815,
    "project":{
    "id":120,
    "name":"Company final evaluation",
    "slug":"first-internship-company-final-evaluation",
    "parent_id":118
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-06-25T14:23:57.079Z",
    "marked":true
    },
    {
    "id":685664,
    "occurrence":0,
    "final_mark":null,
    "status":"searching_a_group",
    "validated?":null,
    "current_team_id":null,
    "project":{
    "id":122,
    "name":"Taskmaster",
    "slug":"taskmaster",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":527347,
    "occurrence":0,
    "final_mark":null,
    "status":"in_progress",
    "validated?":null,
    "current_team_id":1585006,
    "project":{
    "id":15,
    "name":"Fract'ol",
    "slug":"fract-ol",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":573152,
    "occurrence":0,
    "final_mark":null,
    "status":"in_progress",
    "validated?":null,
    "current_team_id":1640121,
    "project":{
    "id":33,
    "name":"ft_select",
    "slug":"ft_select",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":1193642,
    "occurrence":0,
    "final_mark":97,
    "status":"finished",
    "validated?":true,
    "current_team_id":2366699,
    "project":{
    "id":738,
    "name":"Day 08",
    "slug":"piscine-python-django-day-08",
    "parent_id":727
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-01-20T15:16:39.354Z",
    "marked":true
    },
    {
    "id":1186901,
    "occurrence":0,
    "final_mark":80,
    "status":"finished",
    "validated?":true,
    "current_team_id":2358610,
    "project":{
    "id":732,
    "name":"Day 03",
    "slug":"piscine-python-django-day-03",
    "parent_id":727
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-01-12T10:36:51.350Z",
    "marked":true
    },
    {
    "id":1186900,
    "occurrence":0,
    "final_mark":86,
    "status":"finished",
    "validated?":true,
    "current_team_id":2358609,
    "project":{
    "id":731,
    "name":"Day 02",
    "slug":"piscine-python-django-day-02",
    "parent_id":727
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-01-12T10:38:49.728Z",
    "marked":true
    },
    {
    "id":1305570,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":2490860,
    "project":{
    "id":747,
    "name":"Day 03",
    "slug":"piscine-swift-ios-day-03",
    "parent_id":742
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-04-04T14:59:13.730Z",
    "marked":true
    },
    {
    "id":1305568,
    "occurrence":0,
    "final_mark":84,
    "status":"finished",
    "validated?":true,
    "current_team_id":2490858,
    "project":{
    "id":748,
    "name":"Day 04",
    "slug":"piscine-swift-ios-day-04",
    "parent_id":742
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-04-04T13:41:51.322Z",
    "marked":true
    },
    {
    "id":1312576,
    "occurrence":0,
    "final_mark":70,
    "status":"finished",
    "validated?":true,
    "current_team_id":2499228,
    "project":{
    "id":753,
    "name":"Day 08",
    "slug":"piscine-swift-ios-day-08",
    "parent_id":742
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-04-08T07:03:32.416Z",
    "marked":true
    },
    {
    "id":1187474,
    "occurrence":0,
    "final_mark":121,
    "status":"finished",
    "validated?":true,
    "current_team_id":2363105,
    "project":{
    "id":734,
    "name":"Rush00",
    "slug":"piscine-python-django-rush00",
    "parent_id":727
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-01-19T11:53:36.362Z",
    "marked":true
    },
    {
    "id":1307101,
    "occurrence":0,
    "final_mark":92,
    "status":"finished",
    "validated?":true,
    "current_team_id":2493810,
    "project":{
    "id":749,
    "name":"Rush00",
    "slug":"piscine-swift-ios-rush00",
    "parent_id":742
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-04-04T13:14:14.594Z",
    "marked":true
    },
    {
    "id":1184234,
    "occurrence":0,
    "final_mark":123,
    "status":"finished",
    "validated?":true,
    "current_team_id":2355550,
    "project":{
    "id":727,
    "name":"Piscine Python Django",
    "slug":"piscine-python-django",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-01-25T13:49:19.711Z",
    "marked":true
    },
    {
    "id":754433,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":1855816,
    "project":{
    "id":121,
    "name":"Peer Video",
    "slug":"first-internship-peer-video",
    "parent_id":118
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-09-25T12:26:26.824Z",
    "marked":true
    },
    {
    "id":1201920,
    "occurrence":0,
    "final_mark":70,
    "status":"finished",
    "validated?":true,
    "current_team_id":2376798,
    "project":{
    "id":741,
    "name":"Rush01",
    "slug":"piscine-python-django-rush01",
    "parent_id":727
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-01-25T13:49:18.772Z",
    "marked":true
    },
    {
    "id":1190404,
    "occurrence":0,
    "final_mark":73,
    "status":"finished",
    "validated?":true,
    "current_team_id":2362709,
    "project":{
    "id":735,
    "name":"Day 05",
    "slug":"piscine-python-django-day-05",
    "parent_id":727
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-01-20T13:46:21.503Z",
    "marked":true
    },
    {
    "id":1310070,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":2496291,
    "project":{
    "id":751,
    "name":"Day 06",
    "slug":"piscine-swift-ios-day-06",
    "parent_id":742
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-04-05T12:34:17.924Z",
    "marked":true
    },
    {
    "id":1310005,
    "occurrence":0,
    "final_mark":84,
    "status":"finished",
    "validated?":true,
    "current_team_id":2496206,
    "project":{
    "id":750,
    "name":"Day 05",
    "slug":"piscine-swift-ios-day-05",
    "parent_id":742
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-04-04T13:43:10.029Z",
    "marked":true
    },
    {
    "id":1310071,
    "occurrence":0,
    "final_mark":87,
    "status":"finished",
    "validated?":true,
    "current_team_id":2496292,
    "project":{
    "id":752,
    "name":"Day 07",
    "slug":"piscine-swift-ios-day-07",
    "parent_id":742
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-04-05T13:57:41.841Z",
    "marked":true
    },
    {
    "id":1192194,
    "occurrence":0,
    "final_mark":87,
    "status":"finished",
    "validated?":true,
    "current_team_id":2365056,
    "project":{
    "id":737,
    "name":"Day 07",
    "slug":"piscine-python-django-day-07",
    "parent_id":727
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-01-20T10:39:43.677Z",
    "marked":true
    },
    {
    "id":1191813,
    "occurrence":0,
    "final_mark":87,
    "status":"finished",
    "validated?":true,
    "current_team_id":2364570,
    "project":{
    "id":736,
    "name":"Day 06",
    "slug":"piscine-python-django-day-06",
    "parent_id":727
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-01-20T13:47:56.943Z",
    "marked":true
    },
    {
    "id":1302149,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":2486747,
    "project":{
    "id":744,
    "name":"Day 01",
    "slug":"piscine-swift-ios-day-01",
    "parent_id":742
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-03-28T13:19:37.707Z",
    "marked":true
    },
    {
    "id":1302148,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":2486746,
    "project":{
    "id":743,
    "name":"Day 00",
    "slug":"piscine-swift-ios-day-00",
    "parent_id":742
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-03-28T15:20:03.719Z",
    "marked":true
    },
    {
    "id":1302147,
    "occurrence":0,
    "final_mark":125,
    "status":"finished",
    "validated?":true,
    "current_team_id":2486745,
    "project":{
    "id":742,
    "name":"Piscine Swift iOS",
    "slug":"piscine-swift-ios",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-04-11T14:58:08.880Z",
    "marked":true
    },
    {
    "id":1302583,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":2487269,
    "project":{
    "id":745,
    "name":"Day 02",
    "slug":"piscine-swift-ios-day-02",
    "parent_id":742
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-04-04T13:39:59.587Z",
    "marked":true
    },
    {
    "id":1316160,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":false,
    "current_team_id":2503019,
    "project":{
    "id":754,
    "name":"Day 09",
    "slug":"piscine-swift-ios-day-09",
    "parent_id":742
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-04-08T08:04:21.428Z",
    "marked":true
    },
    {
    "id":1316161,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":2505011,
    "project":{
    "id":755,
    "name":"Rush01",
    "slug":"piscine-swift-ios-rush01",
    "parent_id":742
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-04-11T14:58:08.427Z",
    "marked":true
    },
    {
    "id":1197247,
    "occurrence":0,
    "final_mark":21,
    "status":"finished",
    "validated?":false,
    "current_team_id":2370644,
    "project":{
    "id":740,
    "name":"Day 09",
    "slug":"piscine-python-django-day-09",
    "parent_id":727
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-01-20T15:19:25.337Z",
    "marked":true
    },
    {
    "id":1319419,
    "occurrence":0,
    "final_mark":null,
    "status":"in_progress",
    "validated?":null,
    "current_team_id":2507185,
    "project":{
    "id":536,
    "name":"Swifty Companion",
    "slug":"swifty-companion",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":1325529,
    "occurrence":0,
    "final_mark":null,
    "status":"in_progress",
    "validated?":null,
    "current_team_id":2514510,
    "project":{
    "id":984,
    "name":"ft_ssl_md5",
    "slug":"ft_ssl_md5",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":334183,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359498,
    "project":{
    "id":204,
    "name":"20",
    "slug":"piscine-c-day-09-20",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:53.799Z",
    "marked":true
    },
    {
    "id":334176,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359491,
    "project":{
    "id":203,
    "name":"19",
    "slug":"piscine-c-day-09-19",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:54.013Z",
    "marked":true
    },
    {
    "id":334164,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359479,
    "project":{
    "id":196,
    "name":"12",
    "slug":"piscine-c-day-09-12",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:55.013Z",
    "marked":true
    },
    {
    "id":334153,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359468,
    "project":{
    "id":192,
    "name":"08",
    "slug":"piscine-c-day-09-08",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:56.309Z",
    "marked":true
    },
    {
    "id":334151,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1359466,
    "project":{
    "id":191,
    "name":"07",
    "slug":"piscine-c-day-09-07",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:56.731Z",
    "marked":true
    },
    {
    "id":330400,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":true,
    "current_team_id":1355678,
    "project":{
    "id":187,
    "name":"03",
    "slug":"piscine-c-day-09-03",
    "parent_id":167
    },
    "cursus_ids":[
    6
    ],
    "marked_at":"2017-09-01T17:02:57.399Z",
    "marked":true
    },
    {
    "id":542686,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":1604653,
    "project":{
    "id":96,
    "name":"Savoir Relier",
    "slug":"savoir-relier",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-07-12T02:19:46.847Z",
    "marked":true
    },
    {
    "id":927689,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":2059179,
    "project":{
    "id":687,
    "name":"init",
    "slug":"init",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-07-21T20:57:11.883Z",
    "marked":true
    },
    {
    "id":1346215,
    "occurrence":0,
    "final_mark":null,
    "status":"in_progress",
    "validated?":null,
    "current_team_id":2540006,
    "project":{
    "id":818,
    "name":"Red Tetris",
    "slug":"red-tetris",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":709124,
    "occurrence":0,
    "final_mark":116,
    "status":"finished",
    "validated?":true,
    "current_team_id":1799733,
    "project":{
    "id":118,
    "name":"First Internship",
    "slug":"first-internship",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-09-25T12:26:27.580Z",
    "marked":true
    },
    {
    "id":1114026,
    "occurrence":0,
    "final_mark":125,
    "status":"finished",
    "validated?":true,
    "current_team_id":2272733,
    "project":{
    "id":62,
    "name":"Piscine CPP",
    "slug":"piscine-cpp",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-10-14T23:17:56.899Z",
    "marked":true
    },
    {
    "id":1114028,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":2272735,
    "project":{
    "id":63,
    "name":"Day 00",
    "slug":"42-piscine-c-formation-piscine-cpp-day-00",
    "parent_id":62
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-10-03T08:06:14.189Z",
    "marked":true
    },
    {
    "id":1114031,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":2272738,
    "project":{
    "id":64,
    "name":"Day 01",
    "slug":"42-piscine-c-formation-piscine-cpp-day-01",
    "parent_id":62
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-10-04T15:16:10.816Z",
    "marked":true
    },
    {
    "id":1114033,
    "occurrence":0,
    "final_mark":85,
    "status":"finished",
    "validated?":true,
    "current_team_id":2272740,
    "project":{
    "id":65,
    "name":"Day 02",
    "slug":"42-piscine-c-formation-piscine-cpp-day-02",
    "parent_id":62
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-10-05T10:17:02.159Z",
    "marked":true
    },
    {
    "id":1117985,
    "occurrence":0,
    "final_mark":60,
    "status":"finished",
    "validated?":true,
    "current_team_id":2277093,
    "project":{
    "id":67,
    "name":"Day 04",
    "slug":"42-piscine-c-formation-piscine-cpp-day-04",
    "parent_id":62
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-10-07T10:55:35.193Z",
    "marked":true
    },
    {
    "id":1117415,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":2276505,
    "project":{
    "id":66,
    "name":"Day 03",
    "slug":"42-piscine-c-formation-piscine-cpp-day-03",
    "parent_id":62
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-10-06T09:33:24.616Z",
    "marked":true
    },
    {
    "id":1121246,
    "occurrence":0,
    "final_mark":123,
    "status":"finished",
    "validated?":true,
    "current_team_id":2284663,
    "project":{
    "id":69,
    "name":"Rush00",
    "slug":"piscine-cpp-rush00",
    "parent_id":62
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-10-08T10:07:37.864Z",
    "marked":true
    },
    {
    "id":1124819,
    "occurrence":0,
    "final_mark":80,
    "status":"finished",
    "validated?":true,
    "current_team_id":2283985,
    "project":{
    "id":70,
    "name":"Day 05",
    "slug":"42-piscine-c-formation-piscine-cpp-day-05",
    "parent_id":62
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-10-10T12:55:39.545Z",
    "marked":true
    },
    {
    "id":1126011,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":2285903,
    "project":{
    "id":71,
    "name":"Day 06",
    "slug":"42-piscine-c-formation-piscine-cpp-day-06",
    "parent_id":62
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-10-12T17:39:15.458Z",
    "marked":true
    },
    {
    "id":1126479,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":2286366,
    "project":{
    "id":72,
    "name":"Day 07",
    "slug":"42-piscine-c-formation-piscine-cpp-day-07",
    "parent_id":62
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-10-12T18:36:09.590Z",
    "marked":true
    },
    {
    "id":1127542,
    "occurrence":0,
    "final_mark":59,
    "status":"finished",
    "validated?":true,
    "current_team_id":2287570,
    "project":{
    "id":73,
    "name":"Day 08",
    "slug":"42-piscine-c-formation-piscine-cpp-day-08",
    "parent_id":62
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-10-13T09:22:11.404Z",
    "marked":true
    },
    {
    "id":1131051,
    "occurrence":0,
    "final_mark":101,
    "status":"finished",
    "validated?":true,
    "current_team_id":2291538,
    "project":{
    "id":76,
    "name":"Rush01",
    "slug":"piscine-cpp-rush01",
    "parent_id":62
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-10-14T23:17:56.610Z",
    "marked":true
    },
    {
    "id":1133453,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":false,
    "current_team_id":2294209,
    "project":{
    "id":68,
    "name":"Exam00",
    "slug":"piscine-cpp-exam00",
    "parent_id":62
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-10-14T22:08:05.950Z",
    "marked":true
    },
    {
    "id":1133456,
    "occurrence":0,
    "final_mark":0,
    "status":"finished",
    "validated?":false,
    "current_team_id":2294212,
    "project":{
    "id":75,
    "name":"Exam01",
    "slug":"piscine-cpp-exam01",
    "parent_id":62
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-10-14T22:08:12.978Z",
    "marked":true
    },
    {
    "id":1136677,
    "occurrence":0,
    "final_mark":118,
    "status":"finished",
    "validated?":true,
    "current_team_id":2297622,
    "project":{
    "id":36,
    "name":"Malloc",
    "slug":"malloc",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-12-17T14:28:11.281Z",
    "marked":true
    },
    {
    "id":1251887,
    "occurrence":0,
    "final_mark":null,
    "status":"in_progress",
    "validated?":null,
    "current_team_id":2429778,
    "project":{
    "id":184,
    "name":"Part-time",
    "slug":"part-time",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":698524,
    "occurrence":0,
    "final_mark":81,
    "status":"finished",
    "validated?":true,
    "current_team_id":1788747,
    "project":{
    "id":48,
    "name":"Piscine PHP",
    "slug":"piscine-php",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2017-10-16T21:31:14.264Z",
    "marked":true
    },
    {
    "id":1262902,
    "occurrence":0,
    "final_mark":null,
    "status":"in_progress",
    "validated?":null,
    "current_team_id":2442491,
    "project":{
    "id":847,
    "name":"docker-1",
    "slug":"docker-1",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":1276539,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":2457782,
    "project":{
    "id":180,
    "name":"Contract Upload",
    "slug":"part-time-contract-upload",
    "parent_id":184
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-02-27T15:28:51.001Z",
    "marked":true
    },
    {
    "id":1276540,
    "occurrence":0,
    "final_mark":78,
    "status":"finished",
    "validated?":true,
    "current_team_id":2457783,
    "project":{
    "id":181,
    "name":"Duration",
    "slug":"part-time-duration",
    "parent_id":184
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-02-27T15:28:51.732Z",
    "marked":true
    },
    {
    "id":1276541,
    "occurrence":0,
    "final_mark":null,
    "status":"waiting_for_correction",
    "validated?":null,
    "current_team_id":2457784,
    "project":{
    "id":828,
    "name":"Company mid evaluation",
    "slug":"part-time-company-mid-evaluation",
    "parent_id":184
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":1276542,
    "occurrence":0,
    "final_mark":null,
    "status":"waiting_for_correction",
    "validated?":null,
    "current_team_id":2457785,
    "project":{
    "id":182,
    "name":"Company final evaluation",
    "slug":"part-time-company-final-evaluation",
    "parent_id":184
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":1176080,
    "occurrence":0,
    "final_mark":114,
    "status":"finished",
    "validated?":true,
    "current_team_id":2343980,
    "project":{
    "id":409,
    "name":"ft_hangouts",
    "slug":"ft_hangouts",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-12-07T09:13:21.466Z",
    "marked":true
    },
    {
    "id":1180085,
    "occurrence":0,
    "final_mark":125,
    "status":"finished",
    "validated?":true,
    "current_team_id":2350309,
    "project":{
    "id":604,
    "name":"Darkly",
    "slug":"darkly",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2018-12-19T11:20:34.120Z",
    "marked":true
    },
    {
    "id":1181726,
    "occurrence":0,
    "final_mark":null,
    "status":"in_progress",
    "validated?":null,
    "current_team_id":2352568,
    "project":{
    "id":37,
    "name":"Nm-otool",
    "slug":"nm-otool",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":1181725,
    "occurrence":0,
    "final_mark":null,
    "status":"searching_a_group",
    "validated?":null,
    "current_team_id":null,
    "project":{
    "id":597,
    "name":"Hypertube",
    "slug":"hypertube",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":1181729,
    "occurrence":0,
    "final_mark":null,
    "status":"searching_a_group",
    "validated?":null,
    "current_team_id":null,
    "project":{
    "id":98,
    "name":"Expert System",
    "slug":"expert-system",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":1181728,
    "occurrence":0,
    "final_mark":null,
    "status":"searching_a_group",
    "validated?":null,
    "current_team_id":null,
    "project":{
    "id":97,
    "name":"N-puzzle",
    "slug":"n-puzzle",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":1181727,
    "occurrence":0,
    "final_mark":null,
    "status":"in_progress",
    "validated?":null,
    "current_team_id":2352569,
    "project":{
    "id":700,
    "name":"Dr Quine",
    "slug":"dr-quine",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":1181730,
    "occurrence":0,
    "final_mark":null,
    "status":"in_progress",
    "validated?":null,
    "current_team_id":2352570,
    "project":{
    "id":135,
    "name":"Scop",
    "slug":"scop",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":1181893,
    "occurrence":0,
    "final_mark":null,
    "status":"in_progress",
    "validated?":null,
    "current_team_id":2352663,
    "project":{
    "id":111,
    "name":"ComputorV1",
    "slug":"computorv1",
    "parent_id":null
    },
    "cursus_ids":[
    1
    ],
    "marked_at":null,
    "marked":false
    },
    {
    "id":1184235,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":2355551,
    "project":{
    "id":746,
    "name":"Day 00",
    "slug":"piscine-python-django-day-00",
    "parent_id":727
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-01-09T13:42:31.062Z",
    "marked":true
    },
    {
    "id":1184236,
    "occurrence":0,
    "final_mark":94,
    "status":"finished",
    "validated?":true,
    "current_team_id":2355552,
    "project":{
    "id":730,
    "name":"Day 01",
    "slug":"piscine-python-django-day-01",
    "parent_id":727
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-01-10T10:31:57.972Z",
    "marked":true
    },
    {
    "id":1186902,
    "occurrence":0,
    "final_mark":100,
    "status":"finished",
    "validated?":true,
    "current_team_id":2358611,
    "project":{
    "id":733,
    "name":"Day 04",
    "slug":"piscine-python-django-day-04",
    "parent_id":727
    },
    "cursus_ids":[
    1
    ],
    "marked_at":"2019-01-14T14:22:32.493Z",
    "marked":true
    }
    ],
    "languages_users":[
    {
    "id":20828,
    "language_id":1,
    "user_id":20021,
    "position":1,
    "created_at":"2016-08-07T21:34:30.389Z"
    }
    ],
    "achievements":[
    {
    "id":40,
    "name":"404 - Sleep not found",
    "description":"Etre logué 24h de suite. (à bosser, ofc !)",
    "tier":"easy",
    "kind":"scolarity",
    "visible":true,
    "image":"/uploads/achievement/image/40/SCO001.svg",
    "nbr_of_success":null,
    "users_url":"https://api.intra.42.fr/v2/achievements/40/users"
    },
    {
    "id":54,
    "name":"Attendee",
    "description":"Assister à une conférence.",
    "tier":"none",
    "kind":"scolarity",
    "visible":true,
    "image":"/uploads/achievement/image/54/SCO003.svg",
    "nbr_of_success":1,
    "users_url":"https://api.intra.42.fr/v2/achievements/54/users"
    },
    {
    "id":55,
    "name":"Attendee",
    "description":"Assister à 3 conférences.",
    "tier":"none",
    "kind":"scolarity",
    "visible":true,
    "image":"/uploads/achievement/image/55/SCO003.svg",
    "nbr_of_success":3,
    "users_url":"https://api.intra.42.fr/v2/achievements/55/users"
    },
    {
    "id":56,
    "name":"Attendee",
    "description":"Assister à 10 conférences.",
    "tier":"easy",
    "kind":"scolarity",
    "visible":true,
    "image":"/uploads/achievement/image/56/SCO003.svg",
    "nbr_of_success":10,
    "users_url":"https://api.intra.42.fr/v2/achievements/56/users"
    },
    {
    "id":57,
    "name":"Attendee",
    "description":"Assister à 21 conférences.",
    "tier":"medium",
    "kind":"scolarity",
    "visible":true,
    "image":"/uploads/achievement/image/57/SCO003.svg",
    "nbr_of_success":21,
    "users_url":"https://api.intra.42.fr/v2/achievements/57/users"
    },
    {
    "id":169,
    "name":"Bill Gates",
    "description":"Avoir donné 1 point de correction au pool.",
    "tier":"none",
    "kind":"scolarity",
    "visible":true,
    "image":"/uploads/achievement/image/169/BADGE_SCOLARITY_billgates.svg",
    "nbr_of_success":1,
    "users_url":"https://api.intra.42.fr/v2/achievements/169/users"
    },
    {
    "id":170,
    "name":"Bill Gates",
    "description":"Avoir donné 10 points de correction au pool.",
    "tier":"none",
    "kind":"scolarity",
    "visible":true,
    "image":"/uploads/achievement/image/170/BADGE_SCOLARITY_billgates.svg",
    "nbr_of_success":10,
    "users_url":"https://api.intra.42.fr/v2/achievements/170/users"
    },
    {
    "id":17,
    "name":"Bonus Hunter",
    "description":"Valider 1 projet avec la note maximum.",
    "tier":"easy",
    "kind":"project",
    "visible":true,
    "image":"/uploads/achievement/image/17/PRO005.svg",
    "nbr_of_success":1,
    "users_url":"https://api.intra.42.fr/v2/achievements/17/users"
    },
    {
    "id":18,
    "name":"Bonus Hunter",
    "description":"Valider 3 projets avec la note maximum.",
    "tier":"medium",
    "kind":"project",
    "visible":true,
    "image":"/uploads/achievement/image/18/PRO005.svg",
    "nbr_of_success":3,
    "users_url":"https://api.intra.42.fr/v2/achievements/18/users"
    },
    {
    "id":4,
    "name":"Code Explorer",
    "description":"Valider son premier projet.",
    "tier":"none",
    "kind":"project",
    "visible":true,
    "image":"/uploads/achievement/image/4/PRO002.svg",
    "nbr_of_success":1,
    "users_url":"https://api.intra.42.fr/v2/achievements/4/users"
    },
    {
    "id":5,
    "name":"Code Explorer",
    "description":"Valider 3 projets.",
    "tier":"none",
    "kind":"project",
    "visible":true,
    "image":"/uploads/achievement/image/5/PRO002.svg",
    "nbr_of_success":3,
    "users_url":"https://api.intra.42.fr/v2/achievements/5/users"
    },
    {
    "id":6,
    "name":"Code Explorer",
    "description":"Valider 10 projets.",
    "tier":"none",
    "kind":"project",
    "visible":true,
    "image":"/uploads/achievement/image/6/PRO002.svg",
    "nbr_of_success":10,
    "users_url":"https://api.intra.42.fr/v2/achievements/6/users"
    },
    {
    "id":7,
    "name":"Code Explorer",
    "description":"Valider 21 projets.",
    "tier":"none",
    "kind":"project",
    "visible":true,
    "image":"/uploads/achievement/image/7/PRO002.svg",
    "nbr_of_success":21,
    "users_url":"https://api.intra.42.fr/v2/achievements/7/users"
    },
    {
    "id":44,
    "name":"Curious wanderer",
    "description":"S'être logué une fois dans chaque cluster.",
    "tier":"none",
    "kind":"scolarity",
    "visible":true,
    "image":"/uploads/achievement/image/44/SCO002.svg",
    "nbr_of_success":null,
    "users_url":"https://api.intra.42.fr/v2/achievements/44/users"
    },
    {
    "id":46,
    "name":"Film buff",
    "description":"Regarder 1 video sur l'e-learning.",
    "tier":"none",
    "kind":"pedagogy",
    "visible":true,
    "image":"/uploads/achievement/image/46/PED005.svg",
    "nbr_of_success":1,
    "users_url":"https://api.intra.42.fr/v2/achievements/46/users"
    },
    {
    "id":47,
    "name":"Film buff",
    "description":"Regarder 3 videos sur l'e-learning.",
    "tier":"none",
    "kind":"pedagogy",
    "visible":true,
    "image":"/uploads/achievement/image/47/PED005.svg",
    "nbr_of_success":3,
    "users_url":"https://api.intra.42.fr/v2/achievements/47/users"
    },
    {
    "id":48,
    "name":"Film buff",
    "description":"Regarder 10 videos sur l'e-learning.",
    "tier":"none",
    "kind":"pedagogy",
    "visible":true,
    "image":"/uploads/achievement/image/48/PED005.svg",
    "nbr_of_success":10,
    "users_url":"https://api.intra.42.fr/v2/achievements/48/users"
    },
    {
    "id":49,
    "name":"Film buff",
    "description":"Regarder 21 videos sur l'e-learning.",
    "tier":"none",
    "kind":"pedagogy",
    "visible":true,
    "image":"/uploads/achievement/image/49/PED005.svg",
    "nbr_of_success":21,
    "users_url":"https://api.intra.42.fr/v2/achievements/49/users"
    },
    {
    "id":50,
    "name":"Film buff",
    "description":"Regarder 42 videos sur l'e-learning.",
    "tier":"none",
    "kind":"pedagogy",
    "visible":true,
    "image":"/uploads/achievement/image/50/PED005.svg",
    "nbr_of_success":42,
    "users_url":"https://api.intra.42.fr/v2/achievements/50/users"
    },
    {
    "id":45,
    "name":"Home is where the code is",
    "description":"S'être logué dans le même cluster un mois de suite.",
    "tier":"none",
    "kind":"scolarity",
    "visible":true,
    "image":"/uploads/achievement/image/45/SCO002.svg",
    "nbr_of_success":null,
    "users_url":"https://api.intra.42.fr/v2/achievements/45/users"
    },
    {
    "id":82,
    "name":"I have no idea what I'm doing",
    "description":"Faire une soutenance sans avoir validé le projet.",
    "tier":"none",
    "kind":"pedagogy",
    "visible":true,
    "image":"/uploads/achievement/image/82/PED011.svg",
    "nbr_of_success":null,
    "users_url":"https://api.intra.42.fr/v2/achievements/82/users"
    },
    {
    "id":109,
    "name":"I’ll make him an offer he can’t refuse",
    "description":"Participer au programme de parrainage en tant que parrain.",
    "tier":"none",
    "kind":"pedagogy",
    "visible":true,
    "image":"/uploads/achievement/image/109/PED014.svg",
    "nbr_of_success":null,
    "users_url":"https://api.intra.42.fr/v2/achievements/109/users"
    },
    {
    "id":84,
    "name":"I'm reliable !",
    "description":"Participer à 21 soutenances d'affilée sans en manquer aucune.",
    "tier":"easy",
    "kind":"pedagogy",
    "visible":true,
    "image":"/uploads/achievement/image/84/PED009.svg",
    "nbr_of_success":21,
    "users_url":"https://api.intra.42.fr/v2/achievements/84/users"
    },
    {
    "id":41,
    "name":"In the name of Nicolas",
    "description":"Etre logué 90h sur une semaine. (à bosser, comme Nicolas vous l'a conseillé !)",
    "tier":"easy",
    "kind":"scolarity",
    "visible":true,
    "image":"/uploads/achievement/image/41/SCO001.svg",
    "nbr_of_success":null,
    "users_url":"https://api.intra.42.fr/v2/achievements/41/users"
    },
    {
    "id":87,
    "name":"I post, therefore I am",
    "description":"Poster 1 message sur le forum.",
    "tier":"none",
    "kind":"social",
    "visible":true,
    "image":"/uploads/achievement/image/87/SOC005.svg",
    "nbr_of_success":1,
    "users_url":"https://api.intra.42.fr/v2/achievements/87/users"
    },
    {
    "id":36,
    "name":"It's a rich man's world",
    "description":"Avoir 100 points de wallet.",
    "tier":"none",
    "kind":"social",
    "visible":true,
    "image":"/uploads/achievement/image/36/SOC004.svg",
    "nbr_of_success":100,
    "users_url":"https://api.intra.42.fr/v2/achievements/36/users"
    },
    {
    "id":37,
    "name":"It's a rich man's world",
    "description":"Avoir 200 points de wallet.",
    "tier":"none",
    "kind":"social",
    "visible":true,
    "image":"/uploads/achievement/image/37/SOC004.svg",
    "nbr_of_success":200,
    "users_url":"https://api.intra.42.fr/v2/achievements/37/users"
    },
    {
    "id":155,
    "name":"Je voudrais un croissant",
    "description":"Visiter le campus de Paris",
    "tier":"none",
    "kind":"scolarity",
    "visible":true,
    "image":"/uploads/achievement/image/155/BADGE_SCOLARITY_paris.svg",
    "nbr_of_success":null,
    "users_url":"https://api.intra.42.fr/v2/achievements/155/users"
    },
    {
    "id":88,
    "name":"Love me, I'm famous",
    "description":"Avoir été upvoté 1 fois sur le forum.",
    "tier":"none",
    "kind":"social",
    "visible":true,
    "image":"/uploads/achievement/image/88/SOC006.svg",
    "nbr_of_success":1,
    "users_url":"https://api.intra.42.fr/v2/achievements/88/users"
    },
    {
    "id":25,
    "name":"Rigorous Basterd",
    "description":"Valider 3 projets d'affilée (journées de piscines comprises).",
    "tier":"none",
    "kind":"project",
    "visible":true,
    "image":"/uploads/achievement/image/25/PRO010.svg",
    "nbr_of_success":3,
    "users_url":"https://api.intra.42.fr/v2/achievements/25/users"
    },
    {
    "id":26,
    "name":"Rigorous Basterd",
    "description":"Valider 10 projets d'affilée (journées de piscines comprises).",
    "tier":"easy",
    "kind":"project",
    "visible":true,
    "image":"/uploads/achievement/image/26/PRO010.svg",
    "nbr_of_success":10,
    "users_url":"https://api.intra.42.fr/v2/achievements/26/users"
    },
    {
    "id":27,
    "name":"Rigorous Basterd",
    "description":"Valider 21 projets d'affilée (journées de piscines comprises).",
    "tier":"medium",
    "kind":"project",
    "visible":true,
    "image":"/uploads/achievement/image/27/PRO010.svg",
    "nbr_of_success":21,
    "users_url":"https://api.intra.42.fr/v2/achievements/27/users"
    },
    {
    "id":28,
    "name":"Rigorous Basterd",
    "description":"Valider 42 projets d'affilée (journées de piscines comprises).",
    "tier":"hard",
    "kind":"project",
    "visible":true,
    "image":"/uploads/achievement/image/28/PRO010.svg",
    "nbr_of_success":42,
    "users_url":"https://api.intra.42.fr/v2/achievements/28/users"
    },
    {
    "id":39,
    "name":"Sleep is for the weak",
    "description":"Obtenir les achievements \"404 - Sleep not found\" et \"In the name of Nicolas !\"",
    "tier":"none",
    "kind":"scolarity",
    "visible":true,
    "image":"/uploads/achievement/image/39/SCO001.svg",
    "nbr_of_success":null,
    "users_url":"https://api.intra.42.fr/v2/achievements/39/users"
    },
    {
    "id":24,
    "name":"Social Butterfly",
    "description":"Valider 15 projets de groupe, avec 15 partenaires de groupe différents.",
    "tier":"easy",
    "kind":"social",
    "visible":true,
    "image":"/uploads/achievement/image/24/SOC013.svg",
    "nbr_of_success":15,
    "users_url":"https://api.intra.42.fr/v2/achievements/24/users"
    },
    {
    "id":1,
    "name":"Welcome, Cadet !",
    "description":"Tu as réussi ta piscine C. Bienvenue à 42 !",
    "tier":"none",
    "kind":"project",
    "visible":true,
    "image":"/uploads/achievement/image/1/PRO001.svg",
    "nbr_of_success":null,
    "users_url":"https://api.intra.42.fr/v2/achievements/1/users"
    }
    ],
    "titles":[

    ],
    "titles_users":[

    ],
    "partnerships":[

    ],
    "patroned":[

    ],
    "patroning":[
    {
    "id":1497,
    "user_id":40699,
    "godfather_id":20021,
    "ongoing":true,
    "created_at":"2018-11-12T16:00:09.953Z",
    "updated_at":"2018-11-12T16:00:10.015Z"
    },
    {
    "id":1496,
    "user_id":39884,
    "godfather_id":20021,
    "ongoing":true,
    "created_at":"2018-11-12T16:00:09.688Z",
    "updated_at":"2019-03-14T17:00:30.191Z"
    }
    ],
    "expertises_users":[
    {
    "id":20582,
    "expertise_id":36,
    "interested":false,
    "value":3,
    "contact_me":false,
    "created_at":"2018-05-04T11:14:42.386Z",
    "user_id":20021
    },
    {
    "id":20581,
    "expertise_id":27,
    "interested":false,
    "value":3,
    "contact_me":false,
    "created_at":"2018-05-04T11:14:26.841Z",
    "user_id":20021
    },
    {
    "id":20580,
    "expertise_id":58,
    "interested":false,
    "value":4,
    "contact_me":false,
    "created_at":"2018-05-04T11:14:17.175Z",
    "user_id":20021
    },
    {
    "id":20579,
    "expertise_id":18,
    "interested":false,
    "value":3,
    "contact_me":false,
    "created_at":"2018-05-04T11:14:07.904Z",
    "user_id":20021
    },
    {
    "id":20578,
    "expertise_id":30,
    "interested":false,
    "value":3,
    "contact_me":false,
    "created_at":"2018-05-04T11:13:59.561Z",
    "user_id":20021
    },
    {
    "id":9372,
    "expertise_id":6,
    "interested":false,
    "value":3,
    "contact_me":false,
    "created_at":"2017-01-20T11:28:52.173Z",
    "user_id":20021
    },
    {
    "id":9373,
    "expertise_id":16,
    "interested":false,
    "value":1,
    "contact_me":false,
    "created_at":"2017-01-20T11:29:02.327Z",
    "user_id":20021
    },
    {
    "id":9374,
    "expertise_id":8,
    "interested":false,
    "value":1,
    "contact_me":false,
    "created_at":"2017-01-20T11:29:09.356Z",
    "user_id":20021
    },
    {
    "id":9375,
    "expertise_id":45,
    "interested":false,
    "value":2,
    "contact_me":false,
    "created_at":"2017-01-20T11:29:52.928Z",
    "user_id":20021
    }
    ],
    "campus":[
    {
    "id":1,
    "name":"Paris",
    "time_zone":"Europe/Paris",
    "language":{
    "id":1,
    "name":"Français",
    "identifier":"fr",
    "created_at":"2014-11-02T16:43:38.466Z",
    "updated_at":"2019-04-12T09:02:37.662Z"
    },
    "users_count":16282,
    "vogsphere_id":1,
    "country":"France",
    "address":"96, boulevard Bessières",
    "zip":"75017",
    "city":"Paris",
    "website":"http://www.42.fr/",
    "facebook":"https://facebook.com/42born2code",
    "twitter":"https://twitter.com/42born2code"
    }
    ],
    "campus_users":[
    {
    "id":9193,
    "user_id":20021,
    "campus_id":1,
    "is_primary":true
    }
    ]
}


